config/routes.rb
API::Application.routes.draw do

  root :to => "home#index"

  devise_for :users, :controllers => {:registrations => "registrations",
                                      :omniauth_callbacks => "omniauth_callbacks",
                                      :sessions => "sessions"}


  get '/projects',                                            to: 'projects#index',       defaults: { format: 'json' }

  get '/workflows',                                           to: 'workflow#index',       defaults: { format: 'json' }
  get '/workflows/:id',                                       to: 'workflow#show',        defaults: { format: 'json' }

  get '/current_user',                                        to: "users#logged_in_user"
  post '/tutorial_complete',                                  to: "users#tutorial_complete"
  
  get '/projects/stats',                                      to: 'projects#stats'

  get '/workflows/:workflow_id/subjects',                     to: 'subjects#index'
  get '/workflows/:workflow_id/subject_sets',                 to: 'subject_sets#index'
  
  # Subjects
  get '/subjects/:subject_id',                                to: 'subjects#show',         defaults: { format: 'json' }
  get '/subjects',                                            to: 'subjects#index',        defaults: { format: 'json' }
  get '/workflows/:workflow_id/subject_sets/:subject_set_id/subjects/:subject_id',    to: 'subject_sets#show',     defaults: { format: 'json' }
  
  # Subject_sets
  resources :subject_sets, only: [:show, :index], :defaults => { :format => 'json' }  # we are using the _url helper for show, so opting to keep this as resources for now
  get '/subject_sets/terms/:field',                           to: 'subject_sets#name_search'
  
  # Classifications
  get '/classifications/terms/:workflow_id/:annotation_key',  to: 'classifications#terms'
  post '/classifications',                                    to: 'classifications#create'  

  resources :groups, only: [:show, :index], :defaults => { :format => 'json' }

  namespace :admin do
    resources :subject_sets, :subjects, :classifications, :users
    get 'dashboard' => 'dashboard#index'
    get 'data' => 'data#index'
    get 'data/download' => 'data#download'
    get 'signin' => 'auth#signin'
    post 'stats/recalculate' => 'dashboard#recalculate_stats'
  end
  get 'admin' => 'admin/dashboard#index'
  
end

app/models/subject.rb
class Subject
  include Mongoid::Document
  include Mongoid::Timestamps
  include Randomizer

  paginates_per 3

  scope :root, -> { where(type: 'root').asc(:order) }
  scope :active_root, -> { where(type: 'root', status: 'active').asc(:order) }
  scope :by_type, -> (type) { where(type: type) }
  scope :active_non_root, -> { where(:type.ne => 'root', :status => 'active') }
  scope :active, -> { where(status: 'active').asc(:order)  }
  scope :not_bad, -> { where(:status.ne => 'bad').asc(:order)  }
  scope :visible_marks, -> { where(:status.ne => 'bad', :region.ne => nil).asc(:order)  }
  scope :complete, -> { where(status: 'complete').asc(:order)  }
  scope :by_workflow, -> (workflow_id) { where(workflow_id: workflow_id)  }
  scope :by_subject_set, -> (subject_set_id) { where(subject_set_id: subject_set_id).asc(:order)  }
  scope :by_parent_subject, -> (parent_subject_id) { where(parent_subject_id: parent_subject_id) }
  scope :by_group, -> (group_id) { where(group_id: group_id) }
  scope :user_has_not_classified, -> (user_id) { where(:classifying_user_ids.ne => user_id)  }
  scope :user_did_not_create, -> (user_id) { where(:creating_user_ids.ne => user_id)  }

  # This is a hash with one entry per deriv; `standard', 'thumbnail', etc
  field :location,                    type: Hash
  field :type,                        type: String,  default: "root" #options: "root", "secondary"
  field :status,                      type: String,  default: "active" #options: "active", "inactive", "bad", "retired", "complete", "contentious"

  field :meta_data,                   type: Hash
  field :classification_count,        type: Integer, default: 0
  field :random_no,                   type: Float
  field :secondary_subject_count,     type: Integer, default: 0
  field :created_by_user_id,          type: String

  # Need to sort out relationship between these two fields. Are these two fields Is this :shj
  field :retire_count,                type: Integer
  field :flagged_bad_count,           type: Integer
  field :flagged_illegible_count,     type: Integer


  # ROOT SUBJECT concerns:
  field :order,                       type: Integer
  field :name,                        type: String
  field :width,                       type: Integer
  field :height,                      type: Integer
  field :zooniverse_id

  # SECONDARY SUBJECT concerns:
  field :data,                        type: Hash
  field :region,                      type: Hash

  # Denormalized array of user ids that have classified this subject for quick filtering
  field :classifying_user_ids,        type: Array, default: []
  field :deleting_user_ids,           type: Array, default: []
  field :creating_user_ids,           type: Array, default: []

  belongs_to :workflow
  belongs_to :group
  belongs_to :parent_subject, :class_name => "Subject", :foreign_key => "parent_subject_id"
  belongs_to :subject_set, :class_name => "SubjectSet", :foreign_key => "subject_set_id"

  has_many :child_subjects, :class_name => "Subject"
  has_many :classifications, inverse_of: :subject
  has_many :favourites

  # Classifications that generated this subject:
  has_many :parent_classifications, class_name: 'Classification', inverse_of: :child_subject

  after_create :update_subject_set_stats
  after_create :increment_parents_subject_count_by_one, :if => :parent_subject

  # Index for typical query when fetching subjects for Transcribe/Verify:
  index({"status" => 1, "workflow_id" => 1, "classifying_user_ids" => 1}, {background: true})
  # Index for Marking by subject set:
  index({"type" => 1, "subject_set_id" => 1}, {background: true})
  # Index for fetching child subjects for a parent subject, optionally filtering by region NOT NULL
  index({parent_subject_id: 1, status: 1, region: 1})
  

  def thumbnail
    location['thumbnail'].nil? ? location['standard'] : location['thumbnail']
  end

  def update_subject_set_stats
    subject_set.subject_activated_on_workflow(workflow) if ! workflow.nil? && status == 'active'
    subject_set.inc_subject_count_for_workflow(workflow) if ! workflow.nil?
    # subject_set.inc_active_secondary_subject 1 if type != 'root'
  end

  def increment_parents_subject_count_by(count)
    parent_subject.inc(secondary_subject_count: count)
  end

  def increment_parents_subject_count_by_one
    increment_parents_subject_count_by 1
  end

  def increment_retire_count_by_one
    self.inc(retire_count: 1)
    self.check_retire_by_vote
  end

  def increment_flagged_bad_count_by_one
    self.inc(flagged_bad_count: 1)
    self.check_flagged_bad_count
  end

  def increment_flagged_illegible_count_by_one
    self.inc(flagged_illegible_count: 1)
    # AMS: not in place yet.
    # self.flagged_illegible_count
  end

  # Get the workflow task that generated this subject, if any
  def parent_workflow_task
    if ! (_classifications = parent_classifications.limit(1)).empty?
      _classifications.first.workflow_task
    end
  end

  # find all the classifications for subject where task_key == compleletion_assesment_task
  # calculate the percetage vote for retirement (pvr)
  # if pvr is equal or greater than retire_limit, set self.status == retired.
  def check_flagged_bad_count
    if flagged_bad_count >= 3
      self.bad!
      increment_parents_subject_count_by -1 if parent_subject
    end
  end

  # find all the classifications for subject where task_key == compleletion_assesment_task
  # calculate the percetage vote for retirement (pvr)
  # if pvr is equal or greater than retire_limit, set self.status == retired.
  def check_retire_by_vote
    assesment_classifications = classifications.where(task_key: "completion_assessment_task").count
    if assesment_classifications > 2
      percentage_for_retire = retire_count / assesment_classifications.to_f
      if percentage_for_retire >= workflow.retire_limit
        self.retire!
        increment_parents_subject_count_by -1 if parent_subject
      end
    end
  end


  def bad!
    status! 'bad'
    subject_set.subject_deactivated_on_workflow(workflow) if ! workflow.nil?
    # subject_set.inc_complete_secondary_subject 1 if type != 'root'
  end

  def retire!
    return if status == "bad"
    return if classifying_user_ids.length < workflow.retire_limit
    status! 'retired'
    subject_set.subject_completed_on_workflow(workflow) if ! workflow.nil?
    
    # subject_set.inc_complete_secondary_subject 1 if type != 'root'
  end

  def activate!
    status! 'active'
    subject_set.subject_activated_on_workflow(workflow) if ! workflow.nil?
    # subject_set.inc_active_secondary_subject 1 if type != 'root'
  end

  def calculate_most_popular_parent_classification
    annotations = parent_classifications.map { |c| c.annotation }
    buckets = annotations.inject({}) do |h, ann|
      h[ann] ||= 0
      h[ann] += 1
      h
    end
    buckets = buckets.sort_by { |(k,v)| - v }
    buckets.map { |(k,v)| {ann: k, percentage: v.to_f / parent_classifications.count } }.first
  end


  def to_s
    "#{status != 'active' ? "[#{status.capitalize}] " : ''}#{workflow.nil? ? 'Final' : workflow.name.capitalize} Subject (#{type})"
  end


  # Returns hash mapping distinct values for given field to matching count:
  def self.group_by_field(field, match={})
    agg = []
    agg << {"$match" => match } if match
    agg << {"$group" => { "_id" => "$#{field.to_s}", count: {"$sum" =>  1} }}
    self.collection.aggregate(agg).inject({}) do |h, p|
      h[p["_id"]] = p["count"]
      h
    end
  end

  # Same as above, but restricted to Group:
  def self.group_by_field_for_group(group, field, match={})
    self.collection.aggregate([
      {"$match" => { "group_id" => group.id }.merge(match)}, 
      {"$group" => { "_id" => "$#{field.to_s}", count: {"$sum" =>  1} }}

    ]).inject({}) do |h, p|
      h[p["_id"]] = p["count"]
      h
    end
  end


  private

  def status!(status)
    self.status = status
    save
  end
end

app/controllers/admin/subjects_controller.rb
class Admin::SubjectsController < Admin::AdminBaseController

  def show
    @subject = Subject.find params[:id]
  end

  def index
    @subjects = Subject.where(type: "root")
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  respond_to :json

  def index
    user = current_or_guest_user

    workflow_id           = get_objectid :workflow_id
    group_id              = get_objectid :group_id
    subject_set_id        = get_objectid :subject_set_id
    parent_subject_id     = get_objectid :parent_subject_id
    # Note that pagination is kind of useless when randomizing
    random                = get_bool :random, false
    limit                 = get_int :limit, 10
    page                  = get_int :page, 1
    type                  = params[:type]
    # `status` filter must be one of: 'active', 'any'
    status                = ['active','any'].include?(params[:status]) ? params[:status] : 'active'

    @subjects = Subject.page(page).per(limit)

    # Only active subjects?
    @subjects = @subjects.active if status == 'active'

    # Filter by subject type (e.g. 'root')
    @subjects = @subjects.by_type(type) if type

    # Filter by workflow (There should almost always be a workflow_id filter)
    @subjects = @subjects.by_workflow(workflow_id) if workflow_id

    # Filter by subject?
    @subjects = @subjects.by_parent_subject(parent_subject_id) if parent_subject_id

    # Filter by group?
    @subjects = @subjects.by_group(group_id) if group_id

    # Filter by subject set?
    @subjects = @subjects.by_subject_set(subject_set_id) if subject_set_id

    if ! subject_set_id
      # Randomize?
      # @subjects = @subjects.random(limit: limit) if random
      # PB: Above randomization method produces better randomness, but inconsistent totals
      @subjects = @subjects.random_order if random

      # If user/guest active, filter out anything already classified:
      @subjects = @subjects.user_has_not_classified user.id.to_s if ! user.nil?

      # Should we filter out subjects that the user herself created?
      if ! user.nil? && ! (workflow = Workflow.find(workflow_id)).nil? && ! workflow.subjects_classifiable_by_creator
        # Note: creating_user_ids are stored as ObjectIds, so no need to filter on user.id.to_s:
        @subjects = @subjects.user_did_not_create user.id if ! user.nil?
      end
    end

    links = {
      "next" => {
        href: @subjects.next_page.nil? ? nil : url_for(controller: 'subjects', page: @subjects.next_page),
      },
      "prev" => {
        href: @subjects.prev_page.nil? ? nil : url_for(controller: 'subjects', page: @subjects.prev_page)
      }
    }
    respond_with SubjectResultSerializer.new(@subjects, scope: self.view_context), workflow_id: workflow_id, links: links
  end

  def show
    subject_id = get_objectid :subject_id

    links = {
      self: url_for(@subject)
    }
    @subject = Subject.find subject_id
    respond_with SubjectResultSerializer.new(@subject, scope: self.view_context), links: links
  end


end

app/views/admin/subjects/index.html.erb
<h1>All Subjects</h1>

<table class="dashboard-table" id="subjects-table" width="100%">
  <tr>
    <th></th> 
    <th>Status</th>
    <th>Classifications</th>
    <th>2nd Subjects</th>
    <th>Retire Count</th>
    <th>Bad Count</th>
  </tr>

<% @subjects.each do |subject| %>
  <tr>
    <td><%= link_to admin_subject_path(subject) do %><img src="<%= subject.thumbnail %>" width="100"/><% end %></td>
    <td><%= link_to admin_subject_path(subject) do %><%= subject.status %><% end %></td>
    <td> <%= subject.classification_count %> </td> 
    <td> 
      <%= subject.secondary_subject_count %>
      <ul>
      <% if ! subject.child_subjects.empty? %>
        <% show_max = 5 %>
        <% subject.child_subjects.limit(show_max).each do |child| %>
          <li><%= link_to child, admin_subject_path(child) %></li>
        <% end %>
        <% if subject.child_subjects.count > show_max %>
          <li><%= link_to 'More...', admin_subject_path(subject) %></li>
        <% end %>
      <% end %>
      </ul>
    <td> <%= subject.retire_count %> </td> 
    <td> <%= subject.flagged_bad_count %> </td> 
  </tr>
<% end %>
</table>

app/views/admin/subjects/show.html.erb
<%= render partial: 'partials/subject_breadcrumb', locals: {subject: @subject} %>

<div class="core-data">
  <h1><%= @subject %></h1>
  <% if ! @subject.name.nil? %>
    <h1><%= @subject.name %></h1>
  <% end %>

  <img src="<%= @subject.location["standard"] %>" width="300"/>

  <dl>

    <dt>Type</dt>
    <dd><%= @subject.type %><% if @subject.type != 'root' %> (User-defined)<% end %></dd>

    <dt>Status</dt>
    <dd><%= @subject.status %> 
      <% if ! @subject.parent_subject.nil? %>
        <% if @subject.parent_subject.workflow.generates_subjects_method == 'collect-unique'  %>
          <br />(Has <%= @subject.parent_classifications.count %> classifications. <%= @subject.parent_subject.workflow.generates_subjects_after %> total required to activate.)
        <% end %>
        <% if @subject.parent_subject.workflow.generates_subjects_method == 'most-popular'  %>
          <br />(<%= @subject.parent_classifications.count %> parent classification(s) have <%= (100 * @subject.calculate_most_popular_parent_classification[:percentage]).to_i %>% agreement. At least <%= @subject.parent_subject.workflow.generates_subjects_after %> parent classifications with <%= (100 * @subject.parent_subject.workflow.generates_subjects_agreement).to_i %>% agreement required to activate.)
        <% end %>
      <% end %>
      <% if @subject.flagged_bad_count %>
        <br />(<%= @subject.flagged_bad_count %> "Bad Subject" votes)
      <% end %> 
      <% if @subject.retire_count %>
        <br />(<%= @subject.retire_count %> Retire votes)
      <% end %> 
    </dd>

    <dt>Appears in Workflow:</dt>
    <dd>
      <% if @subject.workflow.nil? %>
        &mdash;
      <% else %>
        <%= @subject.workflow.name %>
      <% end %>
    </dd>

    <dt>Source Size:</dt>
    <dd><%= @subject.width %> x <%= @subject.height %></dd>

    <dt>Metadata</dt>
    <dd>
      <% if @subject.meta_data.nil? %>
        &mdash;
      <% else %>
        <%= render partial: 'partials/data_hash', locals: {hash: @subject.meta_data} %> 
      <% end %>
    </dd>


    <dt>Region</dt>
    <dd>
      <% if @subject.region.nil? %>
        &mdash;
      <% else %>
        <%= render partial: 'partials/data_hash', locals: {hash: @subject.region} %> 
      <% end %>
    </dd>

    <dt>Data</dt>
    <dd>
      <% if @subject.data.nil? %>
        &mdash;
      <% else %>
        <%= render partial: 'partials/data_hash', locals: {hash: @subject.data} %> 
      <% end %>
    </dd>

    <dt>Retire Count:</dt>
    <dd> <% if @subject.retire_count.nil? %>&mdash;<% else %><%= @subject.retire_count %><% end %> </dd> 

    <dt>Created</dt>
    <dd><%= @subject.created_at %> (<%= time_ago_in_words @subject.created_at, include_seconds: true %> ago)</dd>

    <dt>Last Update</dt>
    <dd><%= @subject.updated_at %> (<%= time_ago_in_words @subject.updated_at, include_seconds: true %> ago)</dd>

  </dl>
</div>

<div class="supplied-data">
  <h2>Related</h2>

  <% if ! @subject.parent_classifications.empty? %>
    
    <h3>Upstream</h3>
    <dl>

    <% if ! @subject.parent_classifications.empty? %>
      <dt>Generated From These Classifications </dt>
      <dd>
        <ol>
        <% @subject.parent_classifications.each do |classification| %>
          <li><%= link_to "#{classification} (#{time_ago_in_words(classification.finished_at)} ago)", admin_classification_path(classification) %></li>
        <% end %>
        </ol>
      </dd>
    <% end %>

    </dl>

  <% end %>
  
  <h3>Downstream</h3>
  <dl>
    <dt>Total Classifications</dt>
    <dd><%= @subject.classification_count %></dd>

    <dt>Total Child Subjects</dt>
    <dd><%= @subject.secondary_subject_count %></dd>

    <% if @subject.classifications.having_child_subjects.count > 0 %>
      <dt>Subject-Generating Classifications</dt>
      <dd>
        <ol>
        <% @subject.classifications.having_child_subjects.each do |classification| %>
          <li><%= link_to "#{classification} (#{time_ago_in_words(classification.finished_at)} ago)", admin_classification_path(classification) %>
            <br />&raquo; <%= link_to classification.child_subject, admin_subject_path(classification.child_subject) %>
          </li>
        <% end %>
        </ol>
      </dd>
    <% end %>

    <% if @subject.classifications.not_having_child_subjects.count > 0 %>
      <dt><% if @subject.classifications.having_child_subjects.count > 0 %>Other <% end %>Classifications</dt>
      <dd>
        <ol>
        <% @subject.classifications.not_having_child_subjects.each do |classification| %>
          <li><%= link_to "#{classification} (#{time_ago_in_words(classification.finished_at)} ago)", admin_classification_path(classification) %>
          </li>
        <% end %>
        </ol>
      </dd>
    <% end %>
  </dl>
</div>